name: Build Windows EXE
on: [push] # Runs every time you push from Termux

jobs:
  build_job:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Create EXE
        run: npm run dist

      - name: Upload Finished App
        uses: actions/upload-artifact@v4
        with:
          name: TKM-AI-Portable-App
          path: dist/*.exe
